export const LOGIN_REQUEST = "users.LOGIN_REQUEST"
export const LOGIN_SUCCESS = "users.LOGIN_SUCCESS"
export const LOGIN_ERROR = "users.LOGIN_ERROR"

export const SET_TOKEN = "users.SET_TOKEN"

export const SIGNUP_REQUEST = "users.SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "users.SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "users.SIGNUP_ERROR"

export const GET_USER_INFORMATION_REQUESTED = "users.GET_USER_INFORMATION_REQUESTED"
export const GET_USER_INFORMATION_SUCCESS = "users.GET_USER_INFORMATION_SUCCESS"
export const GET_USER_INFORMATION_ERROR = "users.GET_USER_INFORMATION_ERROR"


