export const LOGIN_REQUEST = "users.LOGIN_REQUEST"
export const LOGIN_SUCCESS = "users.LOGIN_SUCCESS"
export const LOGIN_ERROR = "users.LOGIN_ERROR"
export const LOGIN_FAILED = "users.LOGIN_FAILED"
export const LOGIN_INVALID = "users.LOGIN_INVALID"

export const SET_TOKEN_REQUEST = "users.SET_TOKEN_REQUEST"
export const SET_TOKEN_SUCESS = "users.SET_TOKEN_SUCESS"
export const SET_TOKEN_FAIL = "users.SET_TOKENFAIL"

export const SIGNUP_REQUEST = "users.SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "users.SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "users.SIGNUP_ERROR"

export const INDIVIDUAL_SIGNUP_REQUEST = "users.INDIVIDUAL_SIGNUP_REQUEST"
export const INDIVIDUAL_SIGNUP_SUCCESS = "users.INDIVIDUAL_SIGNUP_SUCCESS"
export const INDIVIDUAL_SIGNUP_ERROR = "users.INDIVIDUAL_SIGNUP_ERROR"

export const BUSINESS_SIGNUP_REQUEST = "users.BUSINESS_SIGNUP_REQUEST"
export const BUSINESS_SIGNUP_SUCCESS = "users.BUSINESS_SIGNUP_SUCCESS"
export const BUSINESS_SIGNUP_ERROR = "users.BUSINESS_SIGNUP_ERROR"

export const GET_USER_INFORMATION_REQUESTED =
	"users.GET_USER_INFORMATION_REQUESTED"
export const GET_USER_INFORMATION_SUCCESS = "users.GET_USER_INFORMATION_SUCCESS"
export const GET_USER_INFORMATION_ERROR = "users.GET_USER_INFORMATION_ERROR"

export const GET_USER_DEPOSITS_REQUESTED = "users.GET_USER_DEPOSITS_REQUESTED"
export const GET_USER_DEPOSITS_SUCCESS = "users.GET_USER_DEPOSITS_SUCCESS"
export const GET_USER_DEPOSITS_ERROR = "users.GET_USER_DEPOSITS_ERROR"

export const SEND_USER_ACTIVATION_CODE_REQUESTED =
	"users.GET_USER_ACTIVATION_CODE_REQUESTED"
export const SEND_USER_ACTIVATION_CODE_SUCCESS =
	"users.GET_USER_ACTIVATION_CODE_SUCCESS"
export const SEND_USER_ACTIVATION_CODE_ERROR =
	"users.GET_USER_ACTIVATION_CODE_ERROR"

export const RENEW_USER_ACTIVATION_CODE_REQUESTED =
	"users.RENEW_USER_ACTIVATION_CODE_REQUESTED"
export const RENEW_USER_ACTIVATION_CODE_SUCCESS =
	"users.RENEW_USER_ACTIVATION_CODE_SUCCESS"
export const RENEW_USER_ACTIVATION_CODE_ERROR =
	"users.RENEW_USER_ACTIVATION_CODE_ERROR"

export const GET_USER_TYPES_REQUESTED = "users.GET_USER_TYPES_REQUESTED"
export const GET_USER_TYPES_SUCCESS = "users.GET_USER_TYPES_SUCCESS"
export const GET_USER_TYPES_ERROR = "users.GET_USER_TYPES_ERROR"

export const REQUEST_MFS_REGISTRATION_CODE_REQUESTED =
	"users.REQUEST_MFS_REGISTRATION_CODE_REQUESTED"
export const REQUEST_MFS_REGISTRATION_CODE_SUCCESS =
	"users.REQUEST_MFS_REGISTRATION_CODE_SUCCESS"
export const REQUEST_MFS_REGISTRATION_CODE_FAILED =
	"users.REQUEST_MFS_REGISTRATION_CODE_FAILED"

export const SET_ACCOUNT_TYPES_REQUESTED = "users.SET_ACCOUNT_TYPES_REQUESTED"
export const SET_ACCOUNT_TYPES_SUCCESS = "users.SET_ACCOUNT_TYPES_SUCCESS"
export const SET_ACCOUNT_TYPES_FAIL = "users.SET_ACCOUNT_TYPES_FAIL"

export const SET_SELECTED_ACCOUNT_TYPES_REQUESTED =
	"users.SET_SELECTED_ACCOUNT_TYPES_REQUESTED"
export const SET_SELECTED_ACCOUNT_TYPE_SUCCESS =
	"users.SET_SELECTED_ACCOUNT_TYPE_SUCCESS"
export const SET_SELECTED_ACCOUNT_TYPES_FAIL =
	"users.SET_SELECTED_ACCOUNT_TYPES_FAIL"


export const FETCH_ACCOUNT_TYPES_REQUESTED = "users.FETCH_ACCOUNT_TYPES_REQUESTED"
export const FETCH_ACCOUNT_TYPES_SUCESS = "users.FETCH_ACCOUNT_TYPES_SUCESS"
export const FETCH_ACCOUNT_TYPES_FAIL = "users.FETCH_ACCOUNT_TYPESFAIL"

export const LOG_OUT_REQUESTED = "users.LOG_OUT_REQUESTED"
export const LOG_OUT_SUCESS = "users.LOG_OUT_SUCESS"
export const LOG_OUT_FAIL = "users.LOG_OUTFAIL"