export const LOGIN_REQUEST = "users.LOGIN_REQUEST"
export const LOGIN_SUCCESS = "users.LOGIN_SUCCESS"
export const LOGIN_ERROR = "users.LOGIN_ERROR"
export const LOGIN_FAILED = "users.LOGIN_FAILED"

export const SET_TOKEN = "users.SET_TOKEN"

export const SIGNUP_REQUEST = "users.SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "users.SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "users.SIGNUP_ERROR"

export const GET_USER_INFORMATION_REQUESTED = "users.GET_USER_INFORMATION_REQUESTED"
export const GET_USER_INFORMATION_SUCCESS = "users.GET_USER_INFORMATION_SUCCESS"
export const GET_USER_INFORMATION_ERROR = "users.GET_USER_INFORMATION_ERROR"

export const GET_USER_DEPOSITS_REQUESTED = "users.GET_USER_DEPOSITS_REQUESTED"
export const GET_USER_DEPOSITS_SUCCESS = "users.GET_USER_DEPOSITS_SUCCESS"
export const GET_USER_DEPOSITS_ERROR = "users.GET_USER_DEPOSITS_ERROR"

export const GET_USER_ACTIVATION_CODE_REQUESTED = "users.GET_USER_ACTIVATION_CODE_REQUESTED"
export const GET_USER_ACTIVATION_CODE_SUCCESS = "users.GET_USER_ACTIVATION_CODE_SUCCESS"
export const GET_USER_ACTIVATION_CODE_ERROR = "users.GET_USER_ACTIVATION_CODE_ERROR"

export const RENEW_USER_ACTIVATION_CODE_REQUESTED = "users.RENEW_USER_ACTIVATION_CODE_REQUESTED"
export const RENEW_USER_ACTIVATION_CODE_SUCCESS = "users.RENEW_USER_ACTIVATION_CODE_SUCCESS"
export const RENEW_USER_ACTIVATION_CODE_ERROR = "users.RENEW_USER_ACTIVATION_CODE_ERROR"


