export const IDLE = "processes.IDLE"
export const LOADING = "processes.LOADING"
export const PROCESSING = "processes.PROCESSING"
export const SUCCESS = "processes.SUCCESS"
export const ERROR = "processes.ERROR"
